# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-10-09 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Helpers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalluatemplates',
            name='Text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='luatemplates',
            name='Text',
            field=models.TextField(),
        ),
    ]
