# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from Production.models import *



class SampleProduct(models.Model):
    Name = models.CharField(max_length=255)
    ProductFunction = models.ForeignKey(ProductFunction)
    Modules = models.ManyToManyField(Module)
    ProductType = models.ForeignKey(ProductType)
    AutoGenerated = models.BooleanField(default=False)

    class Meta:
        verbose_name = 'Sample Product'
        verbose_name_plural = 'Sample Products'
        ordering = ['id']

    def __unicode__(self):
        return self.Name

    def getPriceMultiplier(self):
        rating = self.getFullRating()
        value = (rating)**self.ProductFunction.BaseMarketCurvePotential
        value *= (self.ProductFunction.BaseMarketMaxPriceFactor - 1)
        value += 1
        return value

    def getOptimalPrice(self):
        return self.ProductFunction.BaseMarketPrice * self.getPriceMultiplier()

    def getFeatures(self, onlyOthers = False):
        featureList = []
        for module in self.Modules.all():
            for feature in module.Features.all():
                if feature.ProductFeature not in featureList:
                    featureList.append(feature.ProductFeature)

        if onlyOthers:
            for mandatory in self.ProductFunction.MandatoryFeatures.all():
                if mandatory.Feature in featureList:
                    featureList.remove(mandatory.Feature)
            for optional in self.ProductFunction.OptionalFeatures.all():
                if optional.Feature in featureList:
                    featureList.remove(optional.Feature)
            for drawbacks in self.ProductFunction.Drawbacks.all():
                if drawbacks.Feature in featureList:
                    featureList.remove(drawbacks.Feature)
        return featureList


    def getFeatureValues(self, getAll = True):
        featureValues = {}
        for module in self.Modules.all():
            for feature in module.Features.all():
                if feature.ProductFeature.Name in featureValues:
                    featureValues[feature.ProductFeature.Name] += feature.FeatureValue
                else:
                    featureValues[feature.ProductFeature.Name] = feature.FeatureValue
        if getAll:
            for req in self.ProductFunction.MandatoryFeatures.all():
                if req.Feature.Name not in featureValues:
                    featureValues[req.Feature.Name] = 0
            for feat in self.ProductFunction.OptionalFeatures.all():
                if feat.Feature.Name not in featureValues:
                    featureValues[feat.Feature.Name] = 0
            for dbs in self.ProductFunction.Drawbacks.all():
                if dbs.Feature.Name not in featureValues:
                    featureValues[dbs.Feature.Name] = 0
        return featureValues

    def getSortedFeatureValues(self):
        features = self.getFeatureValues()
        sorted = []
        list = features.keys()
        list.sort(key=sortProductFeatures)
        for key in list:
            sorted.append((key, features[key]))
        return sorted

    def getFullRating(self):
        value = 0.0
        value += self.getOptionalRating()
        value += self.getMandatoryRating()
        value += self.getDrawbackRating()
        return value / 3.0

    def getMandatoryRating(self):
        i = 0.0
        n = 0.0
        featureValues = self.getFeatureValues()
        for mandatory in self.ProductFunction.MandatoryFeatures.all():
            if mandatory.Feature.Name in featureValues:
                i += 1
                n += mandatory.getRatingValue(featureValues[mandatory.Feature.Name])
        return 0.5 if i <= 0 else n / i


    def getOptionalRating(self):
        i = 0.0
        n = 0.0
        featureValues = self.getFeatureValues()
        for feature in self.ProductFunction.OptionalFeatures.all():
            if feature.Feature.Name in featureValues:
                i += 1
                n += feature.getRatingValue(featureValues[feature.Feature.Name])
        return 0.5 if i <= 0 else n / i

    def getDrawbackRating(self):
        i = 0.0
        n = 0.0
        featureValues = self.getFeatureValues()
        for feature in self.ProductFunction.Drawbacks.all():
            if feature.Feature.Name in featureValues:
                i += 1
                n += feature.getRatingValue(featureValues[feature.Feature.Name])
        return 0.5 if i <= 0 else -(n / i)+1

    def collectMaterials(self):
        localMaterials = {}
        for module in self.Modules.all():
            for inputMat in module.InputMaterials.all():
                moduleMatQuery = Module.objects.filter(Material=inputMat.Material)
                if moduleMatQuery.exists():
                    inputModMaterials = moduleMatQuery.all()[0].collectMaterials()
                    for inputModMaterialID, inputModMaterial in inputModMaterials.items():
                        inputModMaterial["amount"] *= inputMat.Amount
                        inputModMaterial["totalcost"] *= inputMat.Amount
                        if inputModMaterialID in localMaterials:
                            localMaterials[inputModMaterialID]["amount"] += inputModMaterial["amount"]
                            localMaterials[inputModMaterialID]["totalcost"] += inputModMaterial["totalcost"]
                        else:
                            localMaterials[inputModMaterialID] = inputModMaterial
                else:
                    inputModMaterialID = inputMat.Material.id
                    if inputModMaterialID in localMaterials:
                        localMaterials[inputModMaterialID]["amount"] += inputMat.Amount
                        localMaterials[inputModMaterialID]["totalcost"] += inputMat.Amount * inputMat.Material.getPricePerUnit()
                    else:
                        localMaterials[inputModMaterialID] = {
                            "name": inputMat.Material.Name,
                            "amount": inputMat.Amount,
                            "totalcost": inputMat.Amount * inputMat.Material.getPricePerUnit(),
                            "icon": inputMat.Material.IconAssetID
                        }
        return localMaterials


def sortProductFeatures(featureName):
    feature = ProductFeature.objects.all().filter(Name=featureName)[0]
    if feature is not None:
        if None in feature.MainFeature.all() and len(feature.ComplementaryFeature) > 0:
            return feature.Type * 5 + 0
        elif None in feature.MainFeature.all():
            return feature.Type * 5 + 1
        else:
            return feature.Type * 5 + 2
    return 999
