# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-03-18 17:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Production', '0026_historicalmaterial_historicalmodule_historicalmodulefeature_historicalmodulefeaturerequirement_histo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Modules', models.ManyToManyField(to='Production.Module')),
                ('ProductType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Production.ProductType')),
            ],
        ),
    ]
