# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-03-19 10:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0026_historicalmaterial_historicalmodule_historicalmodulefeature_historicalmodulefeaturerequirement_histo'),
        ('BalancingHelper', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sampleproduct',
            options={'verbose_name': 'Sample Product', 'verbose_name_plural': 'Sample Products'},
        ),
        migrations.RemoveField(
            model_name='sampleproduct',
            name='ProductType',
        ),
        migrations.AddField(
            model_name='sampleproduct',
            name='ProductFunction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Production.ProductFunction'),
            preserve_default=False,
        ),
    ]
