# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-26 15:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BalancingHelper', '0002_auto_20190319_1103'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sampleproduct',
            options={'ordering': ['id'], 'verbose_name': 'Sample Product', 'verbose_name_plural': 'Sample Products'},
        ),
    ]
