# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-05-28 15:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0028_auto_20190326_1642'),
        ('BalancingHelper', '0003_auto_20190326_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampleproduct',
            name='ProductType',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Production.ProductType'),
            preserve_default=False,
        ),
    ]
