# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-07-12 10:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BalancingHelper', '0006_auto_20190617_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalProgressionValues',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Type', models.IntegerField(choices=[(0, 'integer'), (1, 'float'), (2, 'string')], default=0)),
                ('Value', models.CharField(max_length=255)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical Progression Values',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ProgressionValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Type', models.IntegerField(choices=[(0, 'integer'), (1, 'float'), (2, 'string')], default=0)),
                ('Value', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Progression Values',
                'verbose_name_plural': 'Progression Values',
            },
        ),
    ]
