# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-07-12 11:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0043_auto_20190709_1321'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BalancingHelper', '0007_historicalprogressionvalues_progressionvalues'),
    ]

    operations = [
        migrations.CreateModel(
            name='CriticalModulePath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('PathSteps', models.FloatField(default=10)),
                ('ProgressionStart', models.FloatField(default=0)),
                ('ProgressionEnd', models.FloatField(default=100)),
                ('InitialCostStart', models.FloatField(default=50)),
                ('InitialCostEnd', models.FloatField(default=400000)),
                ('MainFeature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Production.ProductFeature')),
                ('Slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Production.ModuleSlotType')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalCriticalModulePath',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('PathSteps', models.FloatField(default=10)),
                ('ProgressionStart', models.FloatField(default=0)),
                ('ProgressionEnd', models.FloatField(default=100)),
                ('InitialCostStart', models.FloatField(default=50)),
                ('InitialCostEnd', models.FloatField(default=400000)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('MainFeature', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Production.ProductFeature')),
                ('Slot', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Production.ModuleSlotType')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical critical module path',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
