# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-07-12 12:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0043_auto_20190709_1321'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BalancingHelper', '0008_criticalmodulepath_historicalcriticalmodulepath'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalModulePathObject',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('PathPosition', models.FloatField(default=1)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('Module', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Production.Module')),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical Module Path Object',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ModulePathObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PathPosition', models.FloatField(default=1)),
                ('Module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Production.Module')),
            ],
            options={
                'verbose_name': 'Module Path Object',
                'verbose_name_plural': 'Module Path Objects',
            },
        ),
        migrations.AlterModelOptions(
            name='criticalmodulepath',
            options={'ordering': ['id'], 'verbose_name': 'Critical Module Path', 'verbose_name_plural': 'Critical Module Paths'},
        ),
        migrations.AlterModelOptions(
            name='historicalcriticalmodulepath',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Critical Module Path'},
        ),
        migrations.AddField(
            model_name='modulepathobject',
            name='Path',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Modules', to='BalancingHelper.CriticalModulePath'),
        ),
        migrations.AddField(
            model_name='historicalmodulepathobject',
            name='Path',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='BalancingHelper.CriticalModulePath'),
        ),
        migrations.AddField(
            model_name='historicalmodulepathobject',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
