# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-07-12 14:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BalancingHelper', '0010_auto_20190712_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criticalmodulepath',
            name='MainFeature',
        ),
        migrations.RemoveField(
            model_name='criticalmodulepath',
            name='NegativeFeatures',
        ),
        migrations.RemoveField(
            model_name='criticalmodulepath',
            name='PositiveFeatures',
        ),
        migrations.RemoveField(
            model_name='criticalmodulepath',
            name='Slot',
        ),
        migrations.RemoveField(
            model_name='historicalcriticalmodulepath',
            name='MainFeature',
        ),
        migrations.RemoveField(
            model_name='historicalcriticalmodulepath',
            name='Slot',
        ),
        migrations.RemoveField(
            model_name='historicalcriticalmodulepath',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalmodulepathobject',
            name='Module',
        ),
        migrations.RemoveField(
            model_name='historicalmodulepathobject',
            name='Path',
        ),
        migrations.RemoveField(
            model_name='historicalmodulepathobject',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='modulepathobject',
            name='Module',
        ),
        migrations.RemoveField(
            model_name='modulepathobject',
            name='Path',
        ),
        migrations.DeleteModel(
            name='CriticalModulePath',
        ),
        migrations.DeleteModel(
            name='HistoricalCriticalModulePath',
        ),
        migrations.DeleteModel(
            name='HistoricalModulePathObject',
        ),
        migrations.DeleteModel(
            name='ModulePathObject',
        ),
    ]
