# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-07-12 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BalancingHelper', '0012_criticalmodulepath_historicalcriticalmodulepath_historicalmodulepathobject_modulepathobject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalprogressionvalues',
            name='Type',
        ),
        migrations.RemoveField(
            model_name='progressionvalues',
            name='Type',
        ),
        migrations.AlterField(
            model_name='historicalprogressionvalues',
            name='Value',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='progressionvalues',
            name='Value',
            field=models.FloatField(),
        ),
    ]
