# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-09-25 10:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0050_auto_20190925_1219'),
        ('BalancingHelper', '0014_auto_20190925_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampleproduct',
            name='ProductType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Production.ProductType'),
        ),
    ]
