# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-10-09 11:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BalancingHelper', '0015_sampleproduct_producttype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criticalmodulepath',
            name='Slot',
        ),
        migrations.RemoveField(
            model_name='historicalcriticalmodulepath',
            name='Slot',
        ),
    ]
