# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-02-20 10:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BalancingHelper', '0016_auto_20191009_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Type', models.IntegerField(choices=[(0, 'integer'), (1, 'float'), (2, 'string')], default=0)),
                ('Value', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Tuning Values',
                'verbose_name_plural': 'Tuning Values',
            },
        ),
        migrations.CreateModel(
            name='HistoricalBalanceValue',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Type', models.IntegerField(choices=[(0, 'integer'), (1, 'float'), (2, 'string')], default=0)),
                ('Value', models.CharField(max_length=255)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical Tuning Values',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.RemoveField(
            model_name='criticalmodulepath',
            name='MainFeature',
        ),
        migrations.RemoveField(
            model_name='criticalmodulepath',
            name='NegativeFeatures',
        ),
        migrations.RemoveField(
            model_name='criticalmodulepath',
            name='PositiveFeatures',
        ),
        migrations.RemoveField(
            model_name='historicalcriticalmodulepath',
            name='MainFeature',
        ),
        migrations.RemoveField(
            model_name='historicalcriticalmodulepath',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalmodulepathobject',
            name='Module',
        ),
        migrations.RemoveField(
            model_name='historicalmodulepathobject',
            name='Path',
        ),
        migrations.RemoveField(
            model_name='historicalmodulepathobject',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalprogressionvalues',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='modulepathobject',
            name='Module',
        ),
        migrations.RemoveField(
            model_name='modulepathobject',
            name='Path',
        ),
        migrations.DeleteModel(
            name='ProgressionValues',
        ),
        migrations.RemoveField(
            model_name='sampleproduct',
            name='Modules',
        ),
        migrations.RemoveField(
            model_name='sampleproduct',
            name='ProductType',
        ),
        migrations.DeleteModel(
            name='CriticalModulePath',
        ),
        migrations.DeleteModel(
            name='HistoricalCriticalModulePath',
        ),
        migrations.DeleteModel(
            name='HistoricalModulePathObject',
        ),
        migrations.DeleteModel(
            name='HistoricalProgressionValues',
        ),
        migrations.DeleteModel(
            name='ModulePathObject',
        ),
        migrations.DeleteModel(
            name='SampleProduct',
        ),
    ]
