# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-02-20 12:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BalancingHelper', '0017_auto_20200220_1103'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='balancevalue',
            options={'verbose_name': 'Balance Values', 'verbose_name_plural': 'Balance Values'},
        ),
        migrations.AlterModelOptions(
            name='historicalbalancevalue',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Balance Values'},
        ),
    ]
