# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-24 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0003_modulestep_stepnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulestep',
            name='StepNumber',
            field=models.IntegerField(default=0),
        ),
    ]
