# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-26 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0004_auto_20180424_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='SizeType',
            field=models.IntegerField(choices=[(0, 'NormalSlot'), (1, 'LargeSlot')]),
        ),
    ]
