# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-07 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0005_auto_20180426_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='IconMonoAssetID',
            field=models.CharField(default='', help_text='The asset id of the monochrome icon of this material.', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='material',
            name='TextSpriteAssetID',
            field=models.CharField(default='', help_text='The asset id of the TMP spritesheet that contains the text-sprite for this material.', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='material',
            name='TextSpriteEntry',
            field=models.CharField(default='', help_text='The name of the icon of this material within the TMP spritesheet', max_length=31),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='material',
            name='IconAssetID',
            field=models.CharField(help_text='The asset id of the icon of this material.', max_length=255),
        ),
    ]
