# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-11 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0009_auto_20180509_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='IconMonoAssetID',
        ),
        migrations.AddField(
            model_name='material',
            name='ModelAssetID',
            field=models.CharField(default='', help_text='The asset id of the model for this material.', max_length=255),
            preserve_default=False,
        ),
    ]
