# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-14 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0010_auto_20180511_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='ModelAssetID',
            field=models.CharField(blank=True, help_text='The asset id of the model for this material.', max_length=255),
        ),
        migrations.AlterField(
            model_name='material',
            name='TextSpriteAssetID',
            field=models.CharField(blank=True, help_text='The asset id of the TMP spritesheet that contains the text-sprite for this material.', max_length=255),
        ),
        migrations.AlterField(
            model_name='material',
            name='TextSpriteEntry',
            field=models.CharField(blank=True, help_text='The name of the icon of this material within the TMP spritesheet', max_length=31),
        ),
    ]
