# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-17 11:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ObjectTypes', '0014_auto_20180917_1315'),
        ('Production', '0015_auto_20180917_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modulestep',
            name='Module',
        ),
        migrations.RemoveField(
            model_name='modulestepinputmaterialamount',
            name='Material',
        ),
        migrations.RemoveField(
            model_name='modulestepinputmaterialamount',
            name='ModuleStep',
        ),
        migrations.RemoveField(
            model_name='modulestepoutputmaterialamount',
            name='Material',
        ),
        migrations.RemoveField(
            model_name='modulestepoutputmaterialamount',
            name='ModuleStep',
        ),
        migrations.DeleteModel(
            name='ModuleStep',
        ),
        migrations.DeleteModel(
            name='ModuleStepInputMaterialAmount',
        ),
        migrations.DeleteModel(
            name='ModuleStepOutputMaterialAmount',
        ),
    ]
