# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-09-26 12:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0016_auto_20180917_1315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='BuyPrice',
            new_name='StackBuyPrice',
        ),
        migrations.RemoveField(
            model_name='material',
            name='SellPrice',
        ),
    ]
