# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-09-28 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0017_auto_20180926_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productfeature',
            name='DefaultValue',
        ),
        migrations.RemoveField(
            model_name='productfeature',
            name='MaxRange',
        ),
        migrations.RemoveField(
            model_name='productfeature',
            name='MinRange',
        ),
        migrations.RemoveField(
            model_name='productfeature',
            name='PropagationType',
        ),
        migrations.RemoveField(
            model_name='productfeature',
            name='Unit',
        ),
        migrations.AddField(
            model_name='productfeature',
            name='SymbolAssetID',
            field=models.CharField(default='unknown', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productfeature',
            name='Type',
            field=models.IntegerField(choices=[(0, 'Maximum'), (1, 'Minimum'), (2, 'Binary')], default=0),
        ),
        migrations.AlterField(
            model_name='modulefeature',
            name='FeatureValue',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='productfeature',
            name='Description',
            field=models.TextField(blank=True),
        ),
    ]
