# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-09-28 12:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0019_productfunction_productfunctionfeaturerequirement'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleFeatureRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FeatureValue', models.IntegerField()),
                ('Module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FeatureRequirements', to='Production.Module')),
                ('ProductFeature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Production.ProductFeature')),
            ],
            options={
                'verbose_name': 'Module Feature Requirement',
                'verbose_name_plural': 'Module Feature Requirements',
            },
        ),
    ]
