# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-09-28 16:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Research', '0001_initial'),
        ('Production', '0020_modulefeaturerequirement'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleResearchDataYield',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.IntegerField()),
                ('Module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ResearchDataYield', to='Production.Module')),
                ('ResearchDataType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Modules', to='Research.ResearchDataType')),
            ],
            options={
                'verbose_name': 'Module Research Data Yield',
                'verbose_name_plural': 'Module Research Data Yields',
            },
        ),
    ]
