# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-23 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0021_moduleresearchdatayield'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfeature',
            name='HelperEmoji',
            field=models.CharField(default=0, max_length=1),
            preserve_default=False,
        ),
    ]
