# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-02-13 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0024_auto_20190207_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfunction',
            name='BaseMarketPrice',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='productfunction',
            name='ViableProductTypes',
            field=models.ManyToManyField(related_name='PossibleFunctions', to='Production.ProductType'),
        ),
    ]
