# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-03-20 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0026_historicalmaterial_historicalmodule_historicalmodulefeature_historicalmodulefeaturerequirement_histo'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmodule',
            name='BaseMarketPrice',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='historicalmodule',
            name='OutputAmount',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='module',
            name='BaseMarketPrice',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='module',
            name='OutputAmount',
            field=models.IntegerField(default=1),
        ),
    ]
