# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-26 15:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0027_auto_20190320_1423'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['id'], 'verbose_name': 'Material', 'verbose_name_plural': 'Materials'},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['id'], 'verbose_name': 'Module', 'verbose_name_plural': 'Modules'},
        ),
        migrations.AlterModelOptions(
            name='productfunction',
            options={'ordering': ['id'], 'verbose_name': 'Product Function', 'verbose_name_plural': 'Product Functions'},
        ),
    ]
