# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-11 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0028_auto_20190326_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmodule',
            name='BaseMarketCapacity',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='module',
            name='BaseMarketCapacity',
            field=models.IntegerField(default=50),
        ),
    ]
