# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-11 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0030_auto_20190611_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproductfunction',
            name='BaseMarketCapacity',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='historicalproductfunction',
            name='MarketRecoveryFactor',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='productfunction',
            name='BaseMarketCapacity',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='productfunction',
            name='MarketRecoveryFactor',
            field=models.FloatField(default=0.5),
        ),
    ]
