# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-06-14 16:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0031_auto_20190611_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproductfeature',
            name='ComplementaryFeature',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Production.ProductFeature'),
        ),
        migrations.AddField(
            model_name='productfeature',
            name='ComplementaryFeature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Complementary', to='Production.ProductFeature'),
        ),
        migrations.AlterField(
            model_name='historicalproductfeature',
            name='Type',
            field=models.IntegerField(choices=[(0, 'Maximum'), (1, 'Minimum'), (2, 'Binary'), (3, 'Additive')], default=2),
        ),
        migrations.AlterField(
            model_name='productfeature',
            name='Type',
            field=models.IntegerField(choices=[(0, 'Maximum'), (1, 'Minimum'), (2, 'Binary'), (3, 'Additive')], default=2),
        ),
    ]
