# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-06-14 17:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Production', '0033_auto_20190614_1834'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalProductFunctionOptionalFeatures',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('IsNegative', models.BooleanField(default=False)),
                ('MinValue', models.IntegerField(default=0)),
                ('MaxValue', models.IntegerField(default=10)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('Function', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Production.ProductFunction')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('Feature', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Production.ProductFeature')),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical Optional Feature',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ProductFunctionOptionalFeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IsNegative', models.BooleanField(default=False)),
                ('MinValue', models.IntegerField(default=0)),
                ('MaxValue', models.IntegerField(default=10)),
                ('Function', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OptionalFeatures', to='Production.ProductFunction')),
                ('Feature', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Production.ProductFeature')),
            ],
            options={
                'verbose_name': 'Optional Feature',
                'verbose_name_plural': 'Optional Features',
            },
        ),
    ]
