# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-06-17 09:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0034_historicalproductfunctionoptionalfeatures_productfunctionoptionalfeatures'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproductfunctionfeaturerequirement',
            name='FeatureValueMax',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='productfunctionfeaturerequirement',
            name='FeatureValueMax',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='historicalproductfunctionoptionalfeatures',
            name='Feature',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Production.ProductFeature'),
        ),
        migrations.AlterField(
            model_name='productfunctionoptionalfeatures',
            name='Feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Production.ProductFeature'),
        ),
    ]
