# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-06-24 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0036_auto_20190623_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproductfunction',
            name='BaseMarketCurvePotential',
            field=models.FloatField(default=2),
        ),
        migrations.AlterField(
            model_name='historicalproductfunction',
            name='BaseMarketMaxPriceFactor',
            field=models.FloatField(default=5),
        ),
        migrations.AlterField(
            model_name='productfunction',
            name='BaseMarketCurvePotential',
            field=models.FloatField(default=2),
        ),
        migrations.AlterField(
            model_name='productfunction',
            name='BaseMarketMaxPriceFactor',
            field=models.FloatField(default=5),
        ),
    ]
