# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-06-24 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0037_auto_20190624_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproductfeature',
            name='ComplementaryFeature',
        ),
        migrations.RemoveField(
            model_name='productfeature',
            name='ComplementaryFeature',
        ),
        migrations.AddField(
            model_name='productfeature',
            name='ComplementaryFeature',
            field=models.ManyToManyField(blank=True, related_name='MainFeature', to='Production.ProductFeature'),
        ),
    ]
