# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-07-04 11:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Production', '0038_auto_20190624_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalProductFunctionDrawbacks',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('MinValue', models.IntegerField(default=0)),
                ('MaxValue', models.IntegerField(default=10)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical Drawback',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ProductFunctionDrawbacks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MinValue', models.IntegerField(default=0)),
                ('MaxValue', models.IntegerField(default=10)),
            ],
            options={
                'verbose_name': 'Drawback',
                'verbose_name_plural': 'Drawbacks',
            },
        ),
        migrations.AlterModelOptions(
            name='historicalproductfunctionfeaturerequirement',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Mandatory Feature'},
        ),
        migrations.AlterModelOptions(
            name='productfunctionfeaturerequirement',
            options={'verbose_name': 'Mandatory Feature', 'verbose_name_plural': 'Mandatory Features'},
        ),
        migrations.RemoveField(
            model_name='historicalproductfunctionoptionalfeatures',
            name='IsNegative',
        ),
        migrations.RemoveField(
            model_name='productfunctionoptionalfeatures',
            name='IsNegative',
        ),
        migrations.AddField(
            model_name='historicalproductfeature',
            name='ComplementaryFeature',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Production.ProductFeature'),
        ),
        migrations.RemoveField(
            model_name='productfeature',
            name='ComplementaryFeature',
        ),
        migrations.AddField(
            model_name='productfeature',
            name='ComplementaryFeature',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MainFeature', to='Production.ProductFeature'),
        ),
        migrations.AddField(
            model_name='productfunctiondrawbacks',
            name='Feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Production.ProductFeature'),
        ),
        migrations.AddField(
            model_name='productfunctiondrawbacks',
            name='Function',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Drawbacks', to='Production.ProductFunction'),
        ),
        migrations.AddField(
            model_name='historicalproductfunctiondrawbacks',
            name='Feature',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Production.ProductFeature'),
        ),
        migrations.AddField(
            model_name='historicalproductfunctiondrawbacks',
            name='Function',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Production.ProductFunction'),
        ),
        migrations.AddField(
            model_name='historicalproductfunctiondrawbacks',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
