# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-07-04 11:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0039_auto_20190704_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfeature',
            name='ComplementaryFeature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MainFeature', to='Production.ProductFeature'),
        ),
    ]
