# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-07-04 11:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0040_auto_20190704_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproductfunctionfeaturerequirement',
            name='FeatureValue',
        ),
        migrations.RemoveField(
            model_name='historicalproductfunctionfeaturerequirement',
            name='FeatureValueMax',
        ),
        migrations.RemoveField(
            model_name='productfunctionfeaturerequirement',
            name='FeatureValue',
        ),
        migrations.RemoveField(
            model_name='productfunctionfeaturerequirement',
            name='FeatureValueMax',
        ),
    ]
