# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-07-04 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0041_auto_20190704_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproductfunctionfeaturerequirement',
            name='MaxValue',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='historicalproductfunctionfeaturerequirement',
            name='MinValue',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='productfunctionfeaturerequirement',
            name='MaxValue',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='productfunctionfeaturerequirement',
            name='MinValue',
            field=models.IntegerField(default=1),
        ),
    ]
