# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-07-11 13:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0043_auto_20190709_1321'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTypeSlotUIPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('productType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SlotUIPositions', to='Production.ProductType')),
                ('slotType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Production.ModuleSlotType')),
            ],
            options={
                'verbose_name': 'ProductType Slot UI Position',
                'verbose_name_plural': 'ProductType Slot UI Positions',
            },
        ),
    ]
