# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-07-12 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0045_auto_20190712_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproductfunction',
            name='Description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='productfunction',
            name='Description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
