# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-08-27 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0046_auto_20190712_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmodule',
            name='AssemblyTime',
            field=models.FloatField(default=5),
        ),
        migrations.AddField(
            model_name='module',
            name='AssemblyTime',
            field=models.FloatField(default=5),
        ),
    ]
