# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-08-29 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0047_auto_20190827_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmaterial',
            name='TextSpriteEntry',
            field=models.CharField(blank=True, help_text='The name of the icon of this material within the TMP spritesheet', max_length=255),
        ),
        migrations.AlterField(
            model_name='material',
            name='TextSpriteEntry',
            field=models.CharField(blank=True, help_text='The name of the icon of this material within the TMP spritesheet', max_length=255),
        ),
    ]
