# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-09-25 10:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Production', '0049_auto_20190925_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalProductType',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Description', models.CharField(blank=True, max_length=255)),
                ('IconAssetID', models.CharField(max_length=255)),
                ('BigImageAssetID', models.CharField(max_length=255)),
                ('BaseMarketPrice', models.IntegerField(default=100)),
                ('BaseMarketMaxPriceFactor', models.FloatField(default=5)),
                ('BaseMarketCurvePotential', models.FloatField(default=2)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical Product Type',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalProductTypeDrawbacks',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('MinValue', models.IntegerField(default=0)),
                ('MaxValue', models.IntegerField(default=10)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('Feature', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Production.ProductFeature')),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical Drawback',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalProductTypeFeatureRequirement',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('MinValue', models.IntegerField(default=1)),
                ('MaxValue', models.IntegerField(default=10)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('Feature', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Production.ProductFeature')),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical Mandatory Feature',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalProductTypeOptionalFeatures',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('MinValue', models.IntegerField(default=0)),
                ('MaxValue', models.IntegerField(default=10)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('Feature', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Production.ProductFeature')),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical Optional Feature',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Description', models.CharField(blank=True, max_length=255)),
                ('IconAssetID', models.CharField(max_length=255)),
                ('BigImageAssetID', models.CharField(max_length=255)),
                ('BaseMarketPrice', models.IntegerField(default=100)),
                ('BaseMarketMaxPriceFactor', models.FloatField(default=5)),
                ('BaseMarketCurvePotential', models.FloatField(default=2)),
                ('Slots', models.ManyToManyField(related_name='UsedInProductType', to='Production.ModuleSlotType')),
            ],
            options={
                'verbose_name': 'Product Type',
                'verbose_name_plural': 'Product Types',
            },
        ),
        migrations.CreateModel(
            name='ProductTypeDrawbacks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MinValue', models.IntegerField(default=0)),
                ('MaxValue', models.IntegerField(default=10)),
                ('Feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DrawbackInProductTypes', to='Production.ProductFeature')),
                ('ProductType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Drawbacks', to='Production.ProductType')),
            ],
            options={
                'verbose_name': 'Drawback',
                'verbose_name_plural': 'Drawbacks',
            },
        ),
        migrations.CreateModel(
            name='ProductTypeFeatureRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MinValue', models.IntegerField(default=1)),
                ('MaxValue', models.IntegerField(default=10)),
                ('Feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RequiredInProductTypes', to='Production.ProductFeature')),
                ('Function', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MandatoryFeatures', to='Production.ProductType')),
            ],
            options={
                'verbose_name': 'Mandatory Feature',
                'verbose_name_plural': 'Mandatory Features',
            },
        ),
        migrations.CreateModel(
            name='ProductTypeOptionalFeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MinValue', models.IntegerField(default=0)),
                ('MaxValue', models.IntegerField(default=10)),
                ('Feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OptionalInProductTypes', to='Production.ProductFeature')),
                ('Function', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OptionalFeatures', to='Production.ProductType')),
            ],
            options={
                'verbose_name': 'Optional Feature',
                'verbose_name_plural': 'Optional Features',
            },
        ),
        migrations.CreateModel(
            name='ProductTypeSlotUIPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('productType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SlotUIPositions', to='Production.ProductType')),
                ('slotType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Production.ModuleSlotType')),
            ],
            options={
                'verbose_name': 'ProductType Slot UI Position',
                'verbose_name_plural': 'ProductType Slot UI Positions',
            },
        ),
        migrations.AddField(
            model_name='historicalproducttypeoptionalfeatures',
            name='Function',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Production.ProductType'),
        ),
        migrations.AddField(
            model_name='historicalproducttypeoptionalfeatures',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalproducttypefeaturerequirement',
            name='Function',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Production.ProductType'),
        ),
        migrations.AddField(
            model_name='historicalproducttypefeaturerequirement',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalproducttypedrawbacks',
            name='ProductType',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Production.ProductType'),
        ),
        migrations.AddField(
            model_name='historicalproducttypedrawbacks',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
