# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-26 14:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Production', '0051_auto_20190925_1817'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalNegativeFeature',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('Min', models.IntegerField(default=1)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical Negative Feature',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPositiveFeature',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('Min', models.IntegerField(default=1)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical Positive Feature',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='NegativeFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Min', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Negative Feature',
                'verbose_name_plural': 'Negative Features',
            },
        ),
        migrations.CreateModel(
            name='PositiveFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Min', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Positive Feature',
                'verbose_name_plural': 'Positive Features',
            },
        ),
        migrations.RemoveField(
            model_name='historicalproducttypedrawbacks',
            name='Feature',
        ),
        migrations.RemoveField(
            model_name='historicalproducttypedrawbacks',
            name='ProductType',
        ),
        migrations.RemoveField(
            model_name='historicalproducttypedrawbacks',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalproducttypefeaturerequirement',
            name='Feature',
        ),
        migrations.RemoveField(
            model_name='historicalproducttypefeaturerequirement',
            name='Function',
        ),
        migrations.RemoveField(
            model_name='historicalproducttypefeaturerequirement',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalproducttypeoptionalfeatures',
            name='Feature',
        ),
        migrations.RemoveField(
            model_name='historicalproducttypeoptionalfeatures',
            name='Function',
        ),
        migrations.RemoveField(
            model_name='historicalproducttypeoptionalfeatures',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='producttypedrawbacks',
            name='Feature',
        ),
        migrations.RemoveField(
            model_name='producttypedrawbacks',
            name='ProductType',
        ),
        migrations.RemoveField(
            model_name='producttypefeaturerequirement',
            name='Feature',
        ),
        migrations.RemoveField(
            model_name='producttypefeaturerequirement',
            name='Function',
        ),
        migrations.RemoveField(
            model_name='producttypeoptionalfeatures',
            name='Feature',
        ),
        migrations.RemoveField(
            model_name='producttypeoptionalfeatures',
            name='Function',
        ),
        migrations.RemoveField(
            model_name='historicalproductfeature',
            name='ComplementaryFeature',
        ),
        migrations.RemoveField(
            model_name='productfeature',
            name='ComplementaryFeature',
        ),
        migrations.DeleteModel(
            name='HistoricalProductTypeDrawbacks',
        ),
        migrations.DeleteModel(
            name='HistoricalProductTypeFeatureRequirement',
        ),
        migrations.DeleteModel(
            name='HistoricalProductTypeOptionalFeatures',
        ),
        migrations.DeleteModel(
            name='ProductTypeDrawbacks',
        ),
        migrations.DeleteModel(
            name='ProductTypeFeatureRequirement',
        ),
        migrations.DeleteModel(
            name='ProductTypeOptionalFeatures',
        ),
        migrations.AddField(
            model_name='positivefeature',
            name='Feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProductTypePositiveFeatures', to='Production.ProductFeature'),
        ),
        migrations.AddField(
            model_name='positivefeature',
            name='ProductType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PositiveFeatures', to='Production.ProductType'),
        ),
        migrations.AddField(
            model_name='negativefeature',
            name='Feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProductTypeNegativeFeatures', to='Production.ProductFeature'),
        ),
        migrations.AddField(
            model_name='negativefeature',
            name='ProductType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='NegativeFeatures', to='Production.ProductType'),
        ),
        migrations.AddField(
            model_name='historicalpositivefeature',
            name='Feature',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Production.ProductFeature'),
        ),
        migrations.AddField(
            model_name='historicalpositivefeature',
            name='ProductType',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Production.ProductType'),
        ),
        migrations.AddField(
            model_name='historicalpositivefeature',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalnegativefeature',
            name='Feature',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Production.ProductFeature'),
        ),
        migrations.AddField(
            model_name='historicalnegativefeature',
            name='ProductType',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Production.ProductType'),
        ),
        migrations.AddField(
            model_name='historicalnegativefeature',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
