# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-09-26 16:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0051_auto_20190925_1817'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTypeField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('productType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='GridFields', to='Production.ProductType')),
            ],
            options={
                'verbose_name': 'Product Type Field',
                'verbose_name_plural': 'Product Type Fields',
            },
        ),
    ]
