# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-09-27 05:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0052_producttypefield'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='GridFields', to='Production.Module')),
            ],
            options={
                'verbose_name': 'Module Field',
                'verbose_name_plural': 'Module Fields',
            },
        ),
    ]
