# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-09-27 09:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0053_modulefield'),
        ('Production', '0054_auto_20190926_1836'),
    ]

    operations = [
    ]
