# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-27 12:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0055_auto_20190927_1422'),
        ('Production', '0055_merge_20190927_1117'),
    ]

    operations = [
    ]
