# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-02 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0056_merge_20190927_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmodule',
            name='SamplingTime',
            field=models.FloatField(default=5),
        ),
        migrations.AddField(
            model_name='module',
            name='SamplingTime',
            field=models.FloatField(default=5),
        ),
    ]
