# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-04 11:12
from __future__ import unicode_literals

import Production.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0057_auto_20191002_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproducttype',
            name='MarketTier',
            field=models.IntegerField(default=1, validators=[Production.models.ValidateMarketTier]),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='MarketTier',
            field=models.IntegerField(default=1, validators=[Production.models.ValidateMarketTier]),
        ),
    ]
