# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-04 12:26
from __future__ import unicode_literals

import Production.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0058_auto_20191004_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproducttype',
            name='MarketTier',
            field=models.IntegerField(default=1, help_text='test', validators=[Production.models.ValidateMarketTier]),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='MarketTier',
            field=models.IntegerField(default=1, help_text='test', validators=[Production.models.ValidateMarketTier]),
        ),
    ]
