# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-10-09 11:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BalancingHelper', '0016_auto_20191009_1357'),
        ('Production', '0060_auto_20191004_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalmoduleslottype',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='producttypeslotuiposition',
            name='productType',
        ),
        migrations.RemoveField(
            model_name='producttypeslotuiposition',
            name='slotType',
        ),
        migrations.RemoveField(
            model_name='historicalmodule',
            name='FitsIntoSlot',
        ),
        migrations.RemoveField(
            model_name='module',
            name='FitsIntoSlot',
        ),
        migrations.RemoveField(
            model_name='producttype',
            name='Slots',
        ),
        migrations.DeleteModel(
            name='HistoricalModuleSlotType',
        ),
        migrations.DeleteModel(
            name='ModuleSlotType',
        ),
        migrations.DeleteModel(
            name='ProductTypeSlotUIPosition',
        ),
    ]
