# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-10-08 15:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Production', '0060_auto_20191004_1335'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalMarketPhase',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('PhaseIndex', models.IntegerField(default=0)),
                ('PriceFactor', models.FloatField(default=1.0)),
                ('DemandFactor', models.FloatField(default=1.0)),
                ('Duration', models.IntegerField(default=30)),
                ('DiscoveryPoints', models.IntegerField(default=1)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('ProductType', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Production.ProductType')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical Market Phase',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='MarketPhase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('PhaseIndex', models.IntegerField(default=0)),
                ('PriceFactor', models.FloatField(default=1.0)),
                ('DemandFactor', models.FloatField(default=1.0)),
                ('Duration', models.IntegerField(default=30)),
                ('DiscoveryPoints', models.IntegerField(default=1)),
                ('ProductType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MarketPhases', to='Production.ProductType')),
            ],
            options={
                'verbose_name': 'Market Phase',
                'verbose_name_plural': 'Market Phases',
            },
        )
    ]
