# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-10-08 15:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0061_auto_20191008_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalnegativefeature',
            name='ProductType',
        ),
        migrations.RemoveField(
            model_name='historicalpositivefeature',
            name='ProductType',
        ),
        migrations.RemoveField(
            model_name='negativefeature',
            name='ProductType',
        ),
        migrations.RemoveField(
            model_name='positivefeature',
            name='ProductType',
        ),
    ]
