# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-10-08 15:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models



class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0061_auto_20191008_1727'),
    ]

    operations = [        
	migrations.AddField(
            model_name='historicalproducttype',
            name='BaseMarketDemand',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='producttype',
            name='BaseMarketDemand',
            field=models.IntegerField(default=10),
        ),
    ]
