# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-10-09 12:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Production', '0061_auto_20191009_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalProductTypeCase',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('CaseModule', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Production.Module')),
                ('ProductType', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Production.ProductType')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical Product Type Case',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ProductTypeCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CaseModule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProductTypesCase', to='Production.Module')),
                ('ProductType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Cases', to='Production.ProductType')),
            ],
            options={
                'verbose_name': 'Product Type Case',
                'verbose_name_plural': 'Product Type Cases',
            },
        ),
        migrations.CreateModel(
            name='ProductTypeCaseBlockingField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('X', models.IntegerField()),
                ('Y', models.IntegerField()),
                ('ProductTypeCase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BlockingGridFields', to='Production.ProductTypeCase')),
            ],
            options={
                'verbose_name': 'Product Type Case blocking Field',
                'verbose_name_plural': 'Product Type Case blocking Fields',
            },
        ),
    ]
