# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-10-15 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0064_auto_20191015_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulecategory',
            name='Order',
            field=models.IntegerField(default=1),
        ),
    ]
