# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-10-23 08:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0065_modulecategory_order'),
        ('Production', '0063_producttype_mandatoryfeatures'),
    ]

    operations = [
    ]
