# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-10-23 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0066_merge_20191023_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulecategory',
            name='IconAssetID',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
