# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-10-25 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0067_modulecategory_iconassetid'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmodule',
            name='Tags',
            field=models.CharField(default='', help_text='Separate multiple tags by comma', max_length=512),
        ),
        migrations.AddField(
            model_name='module',
            name='Tags',
            field=models.CharField(default='', help_text='Separate multiple tags by comma', max_length=512),
        ),
    ]
