# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-10-28 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0068_auto_20191025_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproductfeature',
            name='IsDrawback',
            field=models.BooleanField(default=False, help_text='This is a helper for the views, will not get exported.'),
        ),
        migrations.AddField(
            model_name='productfeature',
            name='IsDrawback',
            field=models.BooleanField(default=False, help_text='This is a helper for the views, will not get exported.'),
        ),
    ]
