# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-11-08 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0070_auto_20191028_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproductfeature',
            name='IsDrawback',
            field=models.BooleanField(default=False, help_text='This is a helper for the views, will get exported.'),
        ),
        migrations.AlterField(
            model_name='productfeature',
            name='IsDrawback',
            field=models.BooleanField(default=False, help_text='This is a helper for the views, will get exported.'),
        ),
    ]
