# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-11-21 10:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0071_auto_20191108_0952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproducttype',
            name='BaseMarketCurvePotential',
        ),
        migrations.RemoveField(
            model_name='historicalproducttype',
            name='BaseMarketMaxPriceFactor',
        ),
        migrations.RemoveField(
            model_name='historicalproducttype',
            name='BigImageAssetID',
        ),
        migrations.RemoveField(
            model_name='producttype',
            name='BaseMarketCurvePotential',
        ),
        migrations.RemoveField(
            model_name='producttype',
            name='BaseMarketMaxPriceFactor',
        ),
        migrations.RemoveField(
            model_name='producttype',
            name='BigImageAssetID',
        ),
    ]
