# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-08 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0073_auto_20200107_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmarketphase',
            name='DisplayNotification',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='marketphase',
            name='DisplayNotification',
            field=models.BooleanField(default=True),
        ),
    ]
