# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-01-10 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0073_auto_20200107_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalmodule',
            name='MarketRecoveryFactor',
        ),
        migrations.RemoveField(
            model_name='module',
            name='MarketRecoveryFactor',
        ),
        migrations.AlterField(
            model_name='historicalmodule',
            name='AssemblyTime',
            field=models.FloatField(default=2),
        ),
        migrations.AlterField(
            model_name='historicalmodule',
            name='BaseMarketPrice',
            field=models.FloatField(default=20),
        ),
        migrations.AlterField(
            model_name='historicalmodule',
            name='SamplingTime',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='module',
            name='AssemblyTime',
            field=models.FloatField(default=2),
        ),
        migrations.AlterField(
            model_name='module',
            name='BaseMarketPrice',
            field=models.FloatField(default=20),
        ),
        migrations.AlterField(
            model_name='module',
            name='SamplingTime',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='historicalmarketphase',
            name='DisplayNotification',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='marketphase',
            name='DisplayNotification',
            field=models.BooleanField(default=True),
        ),
    ]
