# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-02-20 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0074_auto_20200110_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmodule',
            name='BaseMarketCapacity',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='historicalmodule',
            name='BaseMarketPrice',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='module',
            name='BaseMarketCapacity',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='module',
            name='BaseMarketPrice',
            field=models.FloatField(default=0),
        ),
    ]
