# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-03-04 16:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0076_modulecategory_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalmarketphase',
            name='ProductType',
        ),
        migrations.RemoveField(
            model_name='historicalmarketphase',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalnegativefeature',
            name='Feature',
        ),
        migrations.RemoveField(
            model_name='historicalnegativefeature',
            name='MarketPhase',
        ),
        migrations.RemoveField(
            model_name='historicalnegativefeature',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalpositivefeature',
            name='Feature',
        ),
        migrations.RemoveField(
            model_name='historicalpositivefeature',
            name='MarketPhase',
        ),
        migrations.RemoveField(
            model_name='historicalpositivefeature',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='marketphase',
            name='ProductType',
        ),
        migrations.RemoveField(
            model_name='negativefeature',
            name='Feature',
        ),
        migrations.RemoveField(
            model_name='negativefeature',
            name='MarketPhase',
        ),
        migrations.RemoveField(
            model_name='positivefeature',
            name='Feature',
        ),
        migrations.RemoveField(
            model_name='positivefeature',
            name='MarketPhase',
        ),
        migrations.DeleteModel(
            name='HistoricalMarketPhase',
        ),
        migrations.DeleteModel(
            name='HistoricalNegativeFeature',
        ),
        migrations.DeleteModel(
            name='HistoricalPositiveFeature',
        ),
        migrations.DeleteModel(
            name='MarketPhase',
        ),
        migrations.DeleteModel(
            name='NegativeFeature',
        ),
        migrations.DeleteModel(
            name='PositiveFeature',
        ),
    ]
