# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-05-19 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0077_auto_20200304_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproductfeature',
            name='FeatureValue',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='productfeature',
            name='FeatureValue',
            field=models.IntegerField(default=10),
        ),
    ]
