# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-06-08 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0078_auto_20200519_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproductfeature',
            name='FeatureValue',
        ),
        migrations.RemoveField(
            model_name='productfeature',
            name='FeatureValue',
        ),
        migrations.AddField(
            model_name='historicalproductfeature',
            name='PriceBonus',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='productfeature',
            name='PriceBonus',
            field=models.IntegerField(default=10),
        ),
    ]
