# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2021-03-10 16:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Production', '0079_auto_20200608_1028'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalSkillType',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Description', models.TextField(blank=True)),
                ('ExperienceCost', models.IntegerField()),
                ('SuccessPointsCost', models.IntegerField()),
                ('AdditionalHiringCost', models.IntegerField()),
                ('WageIncrease', models.IntegerField()),
                ('RequiredHappiness', models.IntegerField()),
                ('SkillEffectID', models.IntegerField()),
                ('SkillEffectValue', models.FloatField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical Skill Type',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='SkillType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Description', models.TextField(blank=True)),
                ('ExperienceCost', models.IntegerField()),
                ('SuccessPointsCost', models.IntegerField()),
                ('AdditionalHiringCost', models.IntegerField()),
                ('WageIncrease', models.IntegerField()),
                ('RequiredHappiness', models.IntegerField()),
                ('SkillEffectID', models.IntegerField()),
                ('SkillEffectValue', models.FloatField()),
            ],
            options={
                'verbose_name': 'Skill Type',
                'verbose_name_plural': 'Skill Types',
            },
        ),
    ]
