# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2021-04-19 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0080_historicalskilltype_skilltype'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalskilltype',
            name='IconAssetID',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='skilltype',
            name='IconAssetID',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
