# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2021-05-19 14:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0081_auto_20210419_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillTypeCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Description', models.CharField(blank=True, max_length=255)),
                ('Order', models.IntegerField(default=1)),
                ('IconAssetID', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Skill Type Category',
                'verbose_name_plural': 'Skill Type Categories',
            },
        ),
        migrations.AddField(
            model_name='historicalskilltype',
            name='OrderInCategory',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='skilltype',
            name='OrderInCategory',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='historicalskilltype',
            name='Category',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Production.SkillTypeCategory'),
        ),
        migrations.AddField(
            model_name='skilltype',
            name='Category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SkillTypes', to='Production.SkillTypeCategory'),
        ),
    ]
