# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-23 15:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovableProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Width', models.FloatField(blank=True, default=0)),
                ('Height', models.FloatField(blank=True, default=0)),
                ('Radius', models.FloatField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ObjectType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='movableproperty',
            name='ObjectType',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='MovableProperty', to='ObjectTypes.ObjectType'),
        ),
    ]
