# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-24 09:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0002_auto_20180419_1049'),
        ('ObjectTypes', '0002_auto_20180423_1803'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssemblyProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ObjectType', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='AssemblyProperty', to='ObjectTypes.ObjectType')),
            ],
            options={
                'verbose_name': 'Assembly Property',
                'verbose_name_plural': 'Assembly Properties',
            },
        ),
        migrations.CreateModel(
            name='AssemblyPropertySlotAssemblyDuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Duration', models.FloatField()),
                ('AssemblyProperty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PossibleSlotTypes', to='ObjectTypes.AssemblyProperty')),
                ('SlotType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Production.ModuleSlotType')),
            ],
            options={
                'verbose_name': 'Possible SlotType',
                'verbose_name_plural': 'Possible SlotTypes',
            },
        ),
        migrations.CreateModel(
            name='BuildableProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BuildDuration', models.FloatField()),
                ('BuildCost', models.IntegerField()),
                ('ObjectType', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='BuildableProperty', to='ObjectTypes.ObjectType')),
            ],
            options={
                'verbose_name': 'Buildable Property',
                'verbose_name_plural': 'Buildable Properties',
            },
        ),
        migrations.CreateModel(
            name='BuildablePropertyNeededMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.IntegerField(default=0)),
                ('BuildableProperty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='NeededMaterials', to='ObjectTypes.BuildableProperty')),
                ('Material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Production.Material')),
            ],
            options={
                'verbose_name': 'NeededMaterial',
                'verbose_name_plural': 'NeededMaterials',
            },
        ),
        migrations.CreateModel(
            name='BuildsObjectConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BuildsObject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BuildsObjectConnection', to='ObjectTypes.ObjectType')),
                ('BuiltBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BuildsObjectConnection', to='ObjectTypes.BuildableProperty')),
            ],
        ),
        migrations.CreateModel(
            name='CrafterProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ObjectType', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='CrafterProperty', to='ObjectTypes.ObjectType')),
            ],
            options={
                'verbose_name': 'Crafter Property',
                'verbose_name_plural': 'Crafter Properties',
            },
        ),
        migrations.CreateModel(
            name='CrafterPropertyModuleStepDuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Duration', models.FloatField()),
                ('CrafterProperty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PossibleModuleSteps', to='ObjectTypes.CrafterProperty')),
                ('ModuleStep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Production.ModuleStep')),
            ],
            options={
                'verbose_name': 'Possible ModuleStep',
                'verbose_name_plural': 'Possible ModuleSteps',
            },
        ),
        migrations.CreateModel(
            name='IconProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IconAssetID', models.CharField(max_length=255)),
                ('ObjectType', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='IconProperty', to='ObjectTypes.ObjectType')),
            ],
            options={
                'verbose_name': 'Object Look Property',
                'verbose_name_plural': 'Object Look Properties',
            },
        ),
        migrations.CreateModel(
            name='InteractableTilesProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ObjectType', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='InteractableTilesProperty', to='ObjectTypes.ObjectType')),
            ],
            options={
                'verbose_name': 'InteractableTiles Property',
                'verbose_name_plural': 'InteractableTiles Properties',
            },
        ),
        migrations.CreateModel(
            name='InteractableTilesPropertyInteractableTile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('XCoord', models.IntegerField()),
                ('YCoord', models.IntegerField()),
                ('InteractableTilesProperty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='InteractableTiles', to='ObjectTypes.InteractableTilesProperty')),
            ],
            options={
                'verbose_name': 'Interactable tile',
                'verbose_name_plural': 'Interactable tiles',
            },
        ),
        migrations.CreateModel(
            name='InventoryProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SlotType', models.IntegerField(choices=[(0, 'NormalSlot'), (1, 'LargeSlot'), (6, 'ObjectSlot'), (7, 'MaterialSlot')])),
                ('NumberOfSlots', models.IntegerField()),
                ('ObjectType', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='InventoryProperty', to='ObjectTypes.ObjectType')),
            ],
            options={
                'verbose_name': 'Inventory Property',
                'verbose_name_plural': 'Inventory Properties',
            },
        ),
        migrations.CreateModel(
            name='RecurringCostProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RecurringCost', models.IntegerField()),
                ('ObjectType', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='RecurringCostProperty', to='ObjectTypes.ObjectType')),
            ],
            options={
                'verbose_name': 'RecurringCost Property',
                'verbose_name_plural': 'RecurringCost Properties',
            },
        ),
        migrations.CreateModel(
            name='SpecialFlagsProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IsBuyPlace', models.BooleanField(default=False)),
                ('IsSellPlace', models.BooleanField(default=False)),
                ('ObjectType', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='SpecialFlagsProperty', to='ObjectTypes.ObjectType')),
            ],
            options={
                'verbose_name': 'SpecialFlags Property',
                'verbose_name_plural': 'SpecialFlags Properties',
            },
        ),
        migrations.CreateModel(
            name='StaticDimensionProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ObjectType', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='StaticDimensionProperty', to='ObjectTypes.ObjectType')),
            ],
            options={
                'verbose_name': 'StaticDimension Property',
                'verbose_name_plural': 'StaticDimension Properties',
            },
        ),
        migrations.CreateModel(
            name='StaticDimensionPropertyBlockedTile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('XCoord', models.IntegerField()),
                ('YCoord', models.IntegerField()),
                ('StaticDimensionProperty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BlockedTiles', to='ObjectTypes.StaticDimensionProperty')),
            ],
            options={
                'verbose_name': 'Blocked tile',
                'verbose_name_plural': 'Blocked tiles',
            },
        ),
        migrations.CreateModel(
            name='StorageProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SizeType', models.IntegerField(choices=[(0, 'NormalSlot'), (1, 'LargeSlot')])),
                ('ObjectType', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='StorageProperty', to='ObjectTypes.ObjectType')),
            ],
            options={
                'verbose_name': 'Storage Property',
                'verbose_name_plural': 'Storage Properties',
            },
        ),
    ]
