# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-24 09:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ObjectTypes', '0003_assemblyproperty_assemblypropertyslotassemblyduration_buildableproperty_buildablepropertyneededmater'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildsobjectconnection',
            name='BuiltBy',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='BuildsObjectConnection', to='ObjectTypes.BuildableProperty'),
        ),
    ]
