# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-26 10:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ObjectTypes', '0004_auto_20180424_1153'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlueprintPrinterProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PrintingTime', models.FloatField()),
                ('NumberOfOutputSlots', models.IntegerField()),
                ('ObjectType', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='BlueprintPrinterProperty', to='ObjectTypes.ObjectType')),
            ],
            options={
                'verbose_name': 'BlueprintPrinter Property',
                'verbose_name_plural': 'BlueprintPrinter Properties',
            },
        ),
        migrations.AlterModelOptions(
            name='iconproperty',
            options={'verbose_name': 'Icon Property', 'verbose_name_plural': 'Icon Properties'},
        ),
    ]
