# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-14 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ObjectTypes', '0005_auto_20180426_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='iconproperty',
            name='TextSpriteAssetID',
            field=models.CharField(blank=True, help_text='The asset id of the TMP spritesheet that contains the text-sprite for this object.', max_length=255),
        ),
        migrations.AddField(
            model_name='iconproperty',
            name='TextSpriteEntry',
            field=models.CharField(blank=True, help_text='The name of the icon of this object within the TMP spritesheet', max_length=31),
        ),
        migrations.AddField(
            model_name='storageproperty',
            name='ModelAssetID',
            field=models.CharField(blank=True, help_text='The asset id of the model that should be used to display this object in an inventory view.', max_length=255),
        ),
        migrations.AlterField(
            model_name='iconproperty',
            name='IconAssetID',
            field=models.CharField(help_text='The asset id of the icon for this object.', max_length=255),
        ),
    ]
