# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-29 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ObjectTypes', '0006_auto_20180514_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='crafterproperty',
            name='SwitchingTime',
            field=models.FloatField(default=1),
        ),
    ]
