# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-01 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ObjectTypes', '0007_crafterproperty_switchingtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialflagsproperty',
            name='IsTrashCan',
            field=models.BooleanField(default=False),
        ),
    ]
