# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-01 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ObjectTypes', '0009_specialflagsproperty_isdraftingtable'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryproperty',
            name='IsLogistic',
            field=models.BooleanField(default=False, help_text='Only logistic inventories can be used in workplaces.'),
        ),
    ]
