# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-13 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ObjectTypes', '0010_inventoryproperty_islogistic'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialflagsproperty',
            name='IsContractBoard',
            field=models.BooleanField(default=False, help_text='Contract boards allow the player to view and accept open contracts.'),
        ),
    ]
