# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-14 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ObjectTypes', '0011_specialflagsproperty_iscontractboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialflagsproperty',
            name='IsBatchEditor',
            field=models.BooleanField(default=False),
        ),
    ]
