# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-17 11:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0015_auto_20180917_1254'),
        ('ObjectTypes', '0012_specialflagsproperty_isbatcheditor'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrafterPropertyModuleDuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Duration', models.FloatField()),
                ('CrafterProperty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PossibleModules', to='ObjectTypes.CrafterProperty')),
                ('Module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Production.Module')),
            ],
            options={
                'verbose_name': 'Possible Module',
                'verbose_name_plural': 'Possible Modules',
            },
        ),
    ]
