# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-17 11:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ObjectTypes', '0013_crafterpropertymoduleduration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crafterpropertymodulestepduration',
            name='CrafterProperty',
        ),
        migrations.RemoveField(
            model_name='crafterpropertymodulestepduration',
            name='ModuleStep',
        ),
        migrations.DeleteModel(
            name='CrafterPropertyModuleStepDuration',
        ),
    ]
