# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-08 15:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ObjectTypes', '0015_remove_buildableproperty_buildcost'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildablePropertyCanBuildInWorkplace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.IntegerField(choices=[(0, 'production'), (1, 'management'), (2, 'logistics'), (3, 'research')], default=0)),
                ('BuildableProperty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CanBuildInWorkplace', to='ObjectTypes.BuildableProperty')),
            ],
        ),
    ]
