# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-08 15:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ObjectTypes', '0016_buildablepropertycanbuildinworkplace'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buildablepropertycanbuildinworkplace',
            options={'verbose_name': 'CanBuildInWorkplace', 'verbose_name_plural': 'CanBuildInWorkplaces'},
        ),
        migrations.RenameField(
            model_name='buildablepropertycanbuildinworkplace',
            old_name='Type',
            new_name='WorkplaceType',
        ),
        migrations.AlterField(
            model_name='buildablepropertycanbuildinworkplace',
            name='BuildableProperty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CanBuildInWorkplaces', to='ObjectTypes.BuildableProperty'),
        ),
    ]
