# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-09 14:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ObjectTypes', '0017_auto_20181008_1758'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchAndDevelopmentProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CanDoResearch', models.BooleanField(default=False)),
                ('CanDoDevelopment', models.BooleanField(default=False)),
                ('ObjectType', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ResearchAndDevelopmentProperty', to='ObjectTypes.ObjectType')),
            ],
            options={
                'verbose_name': 'Research and Development Property',
                'verbose_name_plural': 'Research and Development Properties',
            },
        ),
        migrations.AlterField(
            model_name='buildablepropertycanbuildinworkplace',
            name='BuildableProperty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CanBuildInWorkplaces', to='ObjectTypes.BuildableProperty'),
        ),
        migrations.AlterField(
            model_name='buildablepropertycanbuildinworkplace',
            name='WorkplaceType',
            field=models.IntegerField(choices=[(0, 'production'), (2, 'management'), (1, 'logistics'), (3, 'research')], default=0),
        ),
    ]
