# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-14 17:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0021_moduleresearchdatayield'),
        ('ObjectTypes', '0018_auto_20181009_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssemblyPropertyProductTypeAssemblyDuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Duration', models.FloatField()),
                ('AssemblyProperty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PossibleProductTypes', to='ObjectTypes.AssemblyProperty')),
                ('ProductType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Production.ProductType')),
            ],
            options={
                'verbose_name': 'Possible ProductType',
                'verbose_name_plural': 'Possible ProductTypes',
            },
        ),
        migrations.RemoveField(
            model_name='assemblypropertyslotassemblyduration',
            name='AssemblyProperty',
        ),
        migrations.RemoveField(
            model_name='assemblypropertyslotassemblyduration',
            name='SlotType',
        ),
        migrations.DeleteModel(
            name='AssemblyPropertySlotAssemblyDuration',
        ),
    ]
