# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-30 11:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ObjectTypes', '0019_auto_20181204_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterfaceNodesProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ObjectType', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='InterfaceNodesProperty', to='ObjectTypes.ObjectType')),
            ],
            options={
                'verbose_name': 'Interface Nodes Property',
                'verbose_name_plural': 'Interface Nodes Properties',
            },
        ),
        migrations.CreateModel(
            name='InterfaceNodesPropertyInterfaceNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('XCoord', models.IntegerField()),
                ('YCoord', models.IntegerField()),
                ('IsInput', models.BooleanField()),
                ('InterfaceNodesProperty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='InterfaceNodes', to='ObjectTypes.InterfaceNodesProperty')),
            ],
            options={
                'verbose_name': 'Interface node',
                'verbose_name_plural': 'Interface nodes',
            },
        ),
    ]
