# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-28 10:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ObjectTypes', '0021_conveyorproperty'),
        ('ObjectTypes', '0021_inventorygroupproperty'),
    ]

    operations = [
    ]
