# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-26 15:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ObjectTypes', '0023_historicalassemblyproperty_historicalassemblypropertyproducttypeassemblyduration_historicalblueprint'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='objecttype',
            options={'ordering': ['id'], 'verbose_name': 'Object Type', 'verbose_name_plural': 'Object Types'},
        ),
    ]
