# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-08-27 15:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ObjectTypes', '0027_auto_20190723_1812'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buildabelcategory',
            options={'verbose_name': 'Buildable Category', 'verbose_name_plural': 'Buildable Categories'},
        ),
    ]
