# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-09-02 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ObjectTypes', '0028_auto_20190827_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalresearchanddevelopmentproperty',
            name='Speed',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='researchanddevelopmentproperty',
            name='Speed',
            field=models.FloatField(default=1),
        ),
    ]
