# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-10-21 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ObjectTypes', '0032_auto_20191021_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalobjectlookproperty',
            name='CanChangeColor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='objectlookproperty',
            name='CanChangeColor',
            field=models.BooleanField(default=False),
        ),
    ]
