# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-02-20 09:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ObjectTypes', '0036_auto_20191115_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buildsobjectconnection',
            name='BuildsObject',
        ),
        migrations.RemoveField(
            model_name='buildsobjectconnection',
            name='BuiltBy',
        ),
        migrations.RemoveField(
            model_name='historicalbuildsobjectconnection',
            name='BuildsObject',
        ),
        migrations.RemoveField(
            model_name='historicalbuildsobjectconnection',
            name='BuiltBy',
        ),
        migrations.RemoveField(
            model_name='historicalbuildsobjectconnection',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='BuildsObjectConnection',
        ),
        migrations.DeleteModel(
            name='HistoricalBuildsObjectConnection',
        ),
    ]
