# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-03-02 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ObjectTypes', '0037_auto_20200220_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalspecialflagsproperty',
            name='IsInventoryDistributor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='specialflagsproperty',
            name='IsInventoryDistributor',
            field=models.BooleanField(default=False),
        ),
    ]
