# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-03-04 13:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ObjectTypes', '0038_auto_20200302_1824'),
        ('ObjectTypes', '0038_buildabelcategory_description'),
    ]

    operations = [
    ]
