# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-03-09 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ObjectTypes', '0038_auto_20200302_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildableproperty',
            name='CanBeBuiltOutdoors',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalbuildableproperty',
            name='CanBeBuiltOutdoors',
            field=models.BooleanField(default=False),
        ),
    ]
