# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-03-09 14:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ObjectTypes', '0039_merge_20200304_1448'),
        ('ObjectTypes', '0039_auto_20200309_1516'),
    ]

    operations = [
    ]
