# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-03-09 15:43
from __future__ import unicode_literals

import bitfield.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ObjectTypes', '0040_merge_20200309_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlagTilesProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ObjectType', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='FlagTilesProperty', to='ObjectTypes.ObjectType')),
            ],
            options={
                'verbose_name': 'Flag Tiles Property',
                'verbose_name_plural': 'Flag Tiles Properties',
            },
        ),
        migrations.CreateModel(
            name='FlagTilesPropertyTile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('XCoord', models.IntegerField()),
                ('YCoord', models.IntegerField()),
                ('Flags', bitfield.models.BitField(['FloorTile', 'ConveyorHatch'], default=0)),
                ('FlagsTilesProperty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Tiles', to='ObjectTypes.FlagTilesProperty')),
            ],
            options={
                'verbose_name': 'Flags tile',
                'verbose_name_plural': 'Flags tiles',
            },
        ),
        migrations.CreateModel(
            name='HistoricalFlagTilesProperty',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('ObjectType', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ObjectTypes.ObjectType')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical Flag Tiles Property',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalFlagTilesPropertyTile',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('XCoord', models.IntegerField()),
                ('YCoord', models.IntegerField()),
                ('Flags', bitfield.models.BitField(['FloorTile', 'ConveyorHatch'], default=0)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('FlagsTilesProperty', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ObjectTypes.FlagTilesProperty')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical Flags tile',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
