# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-04-24 10:24
from __future__ import unicode_literals

import bitfield.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ObjectTypes', '0041_flagtilesproperty_flagtilespropertytile_historicalflagtilesproperty_historicalflagtilespropertytile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buildablepropertycanbuildinworkplace',
            name='BuildableProperty',
        ),
        migrations.RemoveField(
            model_name='historicalbuildablepropertycanbuildinworkplace',
            name='BuildableProperty',
        ),
        migrations.RemoveField(
            model_name='historicalbuildablepropertycanbuildinworkplace',
            name='history_user',
        ),
        migrations.AddField(
            model_name='buildableproperty',
            name='MustBeBuiltInWorkzone',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicalbuildableproperty',
            name='MustBeBuiltInWorkzone',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='flagtilespropertytile',
            name='Flags',
            field=bitfield.models.BitField(['FloorTile', 'ConveyorHatch', 'BlockBuildable'], default=0),
        ),
        migrations.AlterField(
            model_name='historicalflagtilespropertytile',
            name='Flags',
            field=bitfield.models.BitField(['FloorTile', 'ConveyorHatch', 'BlockBuildable'], default=0),
        ),
        migrations.DeleteModel(
            name='BuildablePropertyCanBuildInWorkplace',
        ),
        migrations.DeleteModel(
            name='HistoricalBuildablePropertyCanBuildInWorkplace',
        ),
    ]
