# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-04-24 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ObjectTypes', '0042_auto_20200424_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalspecialflagsproperty',
            name='IsInterfacePallet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='specialflagsproperty',
            name='IsInterfacePallet',
            field=models.BooleanField(default=False),
        ),
    ]
