# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-08-31 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ObjectTypes', '0044_auto_20200619_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='crafterproperty',
            name='AutomaticStorageMultiplier',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='historicalcrafterproperty',
            name='AutomaticStorageMultiplier',
            field=models.IntegerField(default=10),
        ),
    ]
