# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2021-01-20 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ObjectTypes', '0045_auto_20200831_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalspecialflagsproperty',
            name='IsMerger',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalspecialflagsproperty',
            name='IsSplitter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='specialflagsproperty',
            name='IsMerger',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='specialflagsproperty',
            name='IsSplitter',
            field=models.BooleanField(default=False),
        ),
    ]
