# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2021-04-14 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ObjectTypes', '0047_historicalskillrequirementsproperty_skillrequirementsproperty'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalskillrequirementsproperty',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Skill Requirements Property'},
        ),
        migrations.AlterModelOptions(
            name='skillrequirementsproperty',
            options={'verbose_name': 'Skill Requirements Property', 'verbose_name_plural': 'Skill Requirements Properties'},
        ),
        migrations.AddField(
            model_name='buildableproperty',
            name='AddHappinessToWorkzone',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='historicalbuildableproperty',
            name='AddHappinessToWorkzone',
            field=models.FloatField(default=0),
        ),
    ]
