# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2021-05-11 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0081_auto_20210419_1707'),
        ('ObjectTypes', '0048_auto_20210414_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchanddevelopmentproperty',
            name='PossibleModules',
            field=models.ManyToManyField(to='Production.Module'),
        ),
    ]
