# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2022-03-01 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ObjectTypes', '0049_researchanddevelopmentproperty_possiblemodules'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalspecialflagsproperty',
            name='IsBuffer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='specialflagsproperty',
            name='IsBuffer',
            field=models.BooleanField(default=False),
        ),
    ]
