# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2022-03-15 15:28
from __future__ import unicode_literals

import bitfield.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ObjectTypes', '0050_auto_20220301_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flagtilespropertytile',
            name='Flags',
            field=bitfield.models.BitField(['FloorTile', 'ConveyorHatch', 'BlockBuildable', 'NeedsWallTile'], default=0),
        ),
        migrations.AlterField(
            model_name='historicalflagtilespropertytile',
            name='Flags',
            field=bitfield.models.BitField(['FloorTile', 'ConveyorHatch', 'BlockBuildable', 'NeedsWallTile'], default=0),
        ),
    ]
