# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2022-03-24 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ObjectTypes', '0052_auto_20220322_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalspecialflagsproperty',
            name='IsUpgradeableShelf',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='specialflagsproperty',
            name='IsUpgradeableShelf',
            field=models.BooleanField(default=False),
        ),
    ]
