# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-09-28 16:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DevelopmentProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('IconAssetID', models.CharField(max_length=255)),
                ('RequiredProjects', models.ManyToManyField(related_name='RequiredForProjects', to='Research.DevelopmentProject')),
            ],
            options={
                'verbose_name': 'Development Project',
                'verbose_name_plural': 'Development Projects',
            },
        ),
        migrations.CreateModel(
            name='DevelopmentProjectRequiredData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Development Project Required Data',
                'verbose_name_plural': 'Development Project Required Data',
            },
        ),
        migrations.CreateModel(
            name='ResearchDataType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('IconAssetID', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Research Data Type',
                'verbose_name_plural': 'Research Data Types',
            },
        ),
        migrations.AddField(
            model_name='developmentprojectrequireddata',
            name='DataType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DevelopmentProjects', to='Research.ResearchDataType'),
        ),
        migrations.AddField(
            model_name='developmentprojectrequireddata',
            name='DevelopmentProject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RequiredData', to='Research.DevelopmentProject'),
        ),
    ]
