# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-04 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0021_moduleresearchdatayield'),
        ('ObjectTypes', '0015_remove_buildableproperty_buildcost'),
        ('Research', '0002_auto_20180928_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='developmentproject',
            name='UnlocksBuildables',
            field=models.ManyToManyField(blank=True, related_name='UnlockedByResearch', to='ObjectTypes.ObjectType'),
        ),
        migrations.AddField(
            model_name='developmentproject',
            name='UnlocksModules',
            field=models.ManyToManyField(blank=True, related_name='UnlockedByResearch', to='Production.Module'),
        ),
        migrations.AddField(
            model_name='developmentproject',
            name='UnlocksProductTypes',
            field=models.ManyToManyField(blank=True, related_name='UnlockedByResearch', to='Production.ProductType'),
        ),
    ]
