# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-26 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0028_auto_20190326_1642'),
        ('Research', '0004_historicaldevelopmentproject_historicaldevelopmentprojectrequireddata_historicalresearchdatatype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='developmentproject',
            options={'ordering': ['id'], 'verbose_name': 'Development Project', 'verbose_name_plural': 'Development Projects'},
        ),
        migrations.AlterModelOptions(
            name='researchdatatype',
            options={'ordering': ['id'], 'verbose_name': 'Research Data Type', 'verbose_name_plural': 'Research Data Types'},
        ),
        migrations.AddField(
            model_name='developmentproject',
            name='UnlocksProductFunctions',
            field=models.ManyToManyField(blank=True, related_name='UnlockedByResearch', to='Production.ProductFunction'),
        ),
    ]
