# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-07-02 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Research', '0005_auto_20190326_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalresearchdatatype',
            name='Value',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='researchdatatype',
            name='Value',
            field=models.IntegerField(default=100),
        ),
    ]
