# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-07-05 11:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Research', '0006_auto_20190702_1901'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalresearchdatatype',
            old_name='Value',
            new_name='NetWorth',
        ),
        migrations.RenameField(
            model_name='researchdatatype',
            old_name='Value',
            new_name='NetWorth',
        ),
    ]
