# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-07-12 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Research', '0007_auto_20190705_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='developmentproject',
            name='Description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='historicaldevelopmentproject',
            name='Description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
