# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-07-30 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Research', '0008_auto_20190712_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='developmentproject',
            name='IsHidden',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicaldevelopmentproject',
            name='IsHidden',
            field=models.BooleanField(default=True),
        ),
    ]
