# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-09-25 10:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Research', '0009_auto_20190730_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developmentproject',
            name='UnlocksProductFunctions',
        ),
        migrations.RemoveField(
            model_name='developmentproject',
            name='UnlocksProductTypes',
        ),
    ]
