# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-09-25 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0050_auto_20190925_1219'),
        ('Research', '0010_auto_20190925_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='developmentproject',
            name='UnlocksProductTypes',
            field=models.ManyToManyField(blank=True, related_name='UnlockedByResearch', to='Production.ProductType'),
        ),
    ]
