# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-10-07 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Research', '0011_developmentproject_unlocksproducttypes'),
    ]

    operations = [
        migrations.AddField(
            model_name='developmentproject',
            name='DiscoveryPoints',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicaldevelopmentproject',
            name='DiscoveryPoints',
            field=models.IntegerField(default=0),
        ),
    ]
