# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-10-23 10:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Research', '0012_auto_20191007_1029'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Order', models.IntegerField(default=1)),
                ('IconAssetID', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Project Category',
                'verbose_name_plural': 'Project Categories',
            },
        ),
        migrations.AddField(
            model_name='developmentproject',
            name='OrderInCategory',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='historicaldevelopmentproject',
            name='OrderInCategory',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='developmentproject',
            name='Category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Projects', to='Research.ProjectCategory'),
        ),
        migrations.AddField(
            model_name='historicaldevelopmentproject',
            name='Category',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Research.ProjectCategory'),
        ),
    ]
