# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-03-04 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Research', '0014_auto_20191121_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcategory',
            name='Description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
