# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-08-06 14:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('ObjectTypes', '0044_auto_20200619_1348'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Production', '0079_auto_20200608_1028'),
        ('Research', '0015_projectcategory_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalProgressNode',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('IsHidden', models.BooleanField(default=False)),
                ('Description', models.CharField(blank=True, max_length=255)),
                ('IconAssetID', models.CharField(max_length=255)),
                ('Lane', models.IntegerField(default=0)),
                ('Tier', models.IntegerField(default=0)),
                ('RequiredMoney', models.IntegerField(default=0)),
                ('RequiredDiscoveryPoints', models.IntegerField(default=0)),
                ('RequiredSuccessPoints', models.IntegerField(default=0)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical Progress Node',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalProgressNodeRequiredData',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('Amount', models.IntegerField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('DataType', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Research.ResearchDataType')),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical Progress Node Required Data',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ProgressNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('IsHidden', models.BooleanField(default=False)),
                ('Description', models.CharField(blank=True, max_length=255)),
                ('IconAssetID', models.CharField(max_length=255)),
                ('Lane', models.IntegerField(default=0)),
                ('Tier', models.IntegerField(default=0)),
                ('RequiredMoney', models.IntegerField(default=0)),
                ('RequiredDiscoveryPoints', models.IntegerField(default=0)),
                ('RequiredSuccessPoints', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'Progress Node',
                'verbose_name_plural': 'Progress Node',
            },
        ),
        migrations.CreateModel(
            name='ProgressNodeRequiredData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.IntegerField()),
                ('DataType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProgressNodes', to='Research.ResearchDataType')),
                ('DevelopmentProject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RequiredData', to='Research.ProgressNode')),
            ],
            options={
                'verbose_name': 'Progress Node Required Data',
                'verbose_name_plural': 'Progress Node Required Data',
            },
        ),
        migrations.CreateModel(
            name='TreeCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Description', models.CharField(blank=True, max_length=255)),
                ('Order', models.IntegerField(default=1)),
                ('IconAssetID', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Tree Category',
                'verbose_name_plural': 'Tree Categories',
            },
        ),
        migrations.AddField(
            model_name='progressnode',
            name='Category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Nodes', to='Research.TreeCategory'),
        ),
        migrations.AddField(
            model_name='progressnode',
            name='RequiredProjects',
            field=models.ManyToManyField(blank=True, related_name='RequiredForProjects', to='Research.ProgressNode'),
        ),
        migrations.AddField(
            model_name='progressnode',
            name='UnlocksBuildables',
            field=models.ManyToManyField(blank=True, related_name='UnlockedByProject', to='ObjectTypes.ObjectType'),
        ),
        migrations.AddField(
            model_name='progressnode',
            name='UnlocksMarkets',
            field=models.ManyToManyField(blank=True, related_name='UnlockedByProject', to='Production.ProductType'),
        ),
        migrations.AddField(
            model_name='historicalprogressnoderequireddata',
            name='DevelopmentProject',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Research.ProgressNode'),
        ),
        migrations.AddField(
            model_name='historicalprogressnoderequireddata',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalprogressnode',
            name='Category',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Research.TreeCategory'),
        ),
        migrations.AddField(
            model_name='historicalprogressnode',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
