# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-08-31 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Research', '0016_auto_20200806_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprogressnode',
            name='UnlocksPolicies',
            field=models.CommaSeparatedIntegerField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='progressnode',
            name='UnlocksPolicies',
            field=models.CommaSeparatedIntegerField(default='', max_length=500),
        ),
    ]
