# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-09-14 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Research', '0019_auto_20200831_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='developmentproject',
            name='Lane',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicaldevelopmentproject',
            name='Lane',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='historicalprogressnode',
            name='Category',
            field=models.IntegerField(choices=[(1, 'cat_tree_bizdev'), (2, 'cat_tree_market')], default=1),
        ),
        migrations.AlterField(
            model_name='progressnode',
            name='Category',
            field=models.IntegerField(choices=[(1, 'cat_tree_bizdev'), (2, 'cat_tree_market')], default=1),
        ),
    ]
