# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-09-14 15:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Research', '0020_auto_20200914_1732'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TreeCategory',
        ),
    ]
