# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2021-01-20 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Research', '0021_delete_treecategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprogressnode',
            name='Category',
            field=models.IntegerField(choices=[(1, 'cat_tree_bizdev'), (2, 'cat_tree_market'), (99, 'cat_tree_custom')], default=1),
        ),
        migrations.AlterField(
            model_name='progressnode',
            name='Category',
            field=models.IntegerField(choices=[(1, 'cat_tree_bizdev'), (2, 'cat_tree_market'), (99, 'cat_tree_custom')], default=1),
        ),
    ]
