# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2021-04-15 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0080_historicalskilltype_skilltype'),
        ('Research', '0022_auto_20210120_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressnode',
            name='UnlocksSkills',
            field=models.ManyToManyField(blank=True, related_name='UnlockedByProject', to='Production.SkillType'),
        ),
    ]
