# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2021-05-25 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Research', '0023_progressnode_unlocksskills'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprogressnode',
            name='NodeGroup',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalprogressnode',
            name='NodeNetWorth',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='progressnode',
            name='NodeGroup',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='progressnode',
            name='NodeNetWorth',
            field=models.IntegerField(default=0),
        ),
    ]
