# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2022-01-11 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Research', '0024_auto_20210525_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalresearchdatatype',
            name='DevelopmentTime',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='researchdatatype',
            name='DevelopmentTime',
            field=models.FloatField(default=1),
        ),
    ]
