# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-08 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TuningValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Type', models.IntegerField(choices=[(0, 'integer'), (1, 'float'), (2, 'string')], default=0)),
                ('Value', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Tuning Values',
                'verbose_name_plural': 'Tuning Values',
            },
        ),
    ]
